name: Build and Dockerize

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Analizar codigo con Sonarqube
      run: mvn verify sonar:sonar \
        -Dsonar.projectKey=helloinfra \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Build con Maven
      run: mvn clean package

    - name: Construir imagen Docker
      run: |
        docker build -t helloinfra:latest .

    - name: Escanear imagen con Trivy
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: helloinfra:latest
        format: table
        exit-code: 0
        ignore-unfixed: true
